# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ai_service_pb2 as ai__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AiServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SuggestSmartField = channel.unary_unary(
                '/nagai.ai.AiService/SuggestSmartField',
                request_serializer=ai__service__pb2.SmartFieldRequest.SerializeToString,
                response_deserializer=ai__service__pb2.SmartFieldResponse.FromString,
                _registered_method=True)
        self.GenerateChecklistItem = channel.unary_unary(
                '/nagai.ai.AiService/GenerateChecklistItem',
                request_serializer=ai__service__pb2.ChecklistItemRequest.SerializeToString,
                response_deserializer=ai__service__pb2.ChecklistItemResponse.FromString,
                _registered_method=True)
        self.GenerateFullChecklist = channel.unary_unary(
                '/nagai.ai.AiService/GenerateFullChecklist',
                request_serializer=ai__service__pb2.FullChecklistRequest.SerializeToString,
                response_deserializer=ai__service__pb2.FullChecklistResponse.FromString,
                _registered_method=True)
        self.GenerateDailyChecklist = channel.unary_unary(
                '/nagai.ai.AiService/GenerateDailyChecklist',
                request_serializer=ai__service__pb2.DailyChecklistRequest.SerializeToString,
                response_deserializer=ai__service__pb2.DailyChecklistResponse.FromString,
                _registered_method=True)


class AiServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SuggestSmartField(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateChecklistItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateFullChecklist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateDailyChecklist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SuggestSmartField': grpc.unary_unary_rpc_method_handler(
                    servicer.SuggestSmartField,
                    request_deserializer=ai__service__pb2.SmartFieldRequest.FromString,
                    response_serializer=ai__service__pb2.SmartFieldResponse.SerializeToString,
            ),
            'GenerateChecklistItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateChecklistItem,
                    request_deserializer=ai__service__pb2.ChecklistItemRequest.FromString,
                    response_serializer=ai__service__pb2.ChecklistItemResponse.SerializeToString,
            ),
            'GenerateFullChecklist': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateFullChecklist,
                    request_deserializer=ai__service__pb2.FullChecklistRequest.FromString,
                    response_serializer=ai__service__pb2.FullChecklistResponse.SerializeToString,
            ),
            'GenerateDailyChecklist': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateDailyChecklist,
                    request_deserializer=ai__service__pb2.DailyChecklistRequest.FromString,
                    response_serializer=ai__service__pb2.DailyChecklistResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nagai.ai.AiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nagai.ai.AiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SuggestSmartField(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nagai.ai.AiService/SuggestSmartField',
            ai__service__pb2.SmartFieldRequest.SerializeToString,
            ai__service__pb2.SmartFieldResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateChecklistItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nagai.ai.AiService/GenerateChecklistItem',
            ai__service__pb2.ChecklistItemRequest.SerializeToString,
            ai__service__pb2.ChecklistItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateFullChecklist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nagai.ai.AiService/GenerateFullChecklist',
            ai__service__pb2.FullChecklistRequest.SerializeToString,
            ai__service__pb2.FullChecklistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateDailyChecklist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nagai.ai.AiService/GenerateDailyChecklist',
            ai__service__pb2.DailyChecklistRequest.SerializeToString,
            ai__service__pb2.DailyChecklistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
