# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61i_service.proto\x12\x08nagai.ai\"P\n\x11SmartFieldRequest\x12\r\n\x05\x66ield\x18\x01 \x01(\t\x12\x12\n\ngoal_title\x18\x02 \x01(\t\x12\x18\n\x10goal_description\x18\x03 \x01(\t\"(\n\x12SmartFieldResponse\x12\x12\n\nsuggestion\x18\x01 \x01(\t\"\\\n\x14\x43hecklistItemRequest\x12\x12\n\ngoal_title\x18\x01 \x01(\t\x12\x18\n\x10goal_description\x18\x02 \x01(\t\x12\x16\n\x0e\x65xisting_items\x18\x03 \x03(\t\"G\n\x15\x43hecklistItemResponse\x12\r\n\x05title\x18\x01 \x01(\t\x12\r\n\x05notes\x18\x02 \x01(\t\x12\x10\n\x08\x64\x65\x61\x64line\x18\x03 \x01(\t\"D\n\x14\x46ullChecklistRequest\x12\x12\n\ngoal_title\x18\x01 \x01(\t\x12\x18\n\x10goal_description\x18\x02 \x01(\t\"?\n\rChecklistItem\x12\r\n\x05title\x18\x01 \x01(\t\x12\r\n\x05notes\x18\x02 \x01(\t\x12\x10\n\x08\x64\x65\x61\x64line\x18\x03 \x01(\t\"?\n\x15\x46ullChecklistResponse\x12&\n\x05items\x18\x01 \x03(\x0b\x32\x17.nagai.ai.ChecklistItem2\x8f\x02\n\tAiService\x12N\n\x11SuggestSmartField\x12\x1b.nagai.ai.SmartFieldRequest\x1a\x1c.nagai.ai.SmartFieldResponse\x12X\n\x15GenerateChecklistItem\x12\x1e.nagai.ai.ChecklistItemRequest\x1a\x1f.nagai.ai.ChecklistItemResponse\x12X\n\x15GenerateFullChecklist\x12\x1e.nagai.ai.FullChecklistRequest\x1a\x1f.nagai.ai.FullChecklistResponseB \n\x0c\x63om.nagai.aiB\x0e\x41iServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\014com.nagai.aiB\016AiServiceProtoP\001'
  _globals['_SMARTFIELDREQUEST']._serialized_start=30
  _globals['_SMARTFIELDREQUEST']._serialized_end=110
  _globals['_SMARTFIELDRESPONSE']._serialized_start=112
  _globals['_SMARTFIELDRESPONSE']._serialized_end=152
  _globals['_CHECKLISTITEMREQUEST']._serialized_start=154
  _globals['_CHECKLISTITEMREQUEST']._serialized_end=246
  _globals['_CHECKLISTITEMRESPONSE']._serialized_start=248
  _globals['_CHECKLISTITEMRESPONSE']._serialized_end=319
  _globals['_FULLCHECKLISTREQUEST']._serialized_start=321
  _globals['_FULLCHECKLISTREQUEST']._serialized_end=389
  _globals['_CHECKLISTITEM']._serialized_start=391
  _globals['_CHECKLISTITEM']._serialized_end=454
  _globals['_FULLCHECKLISTRESPONSE']._serialized_start=456
  _globals['_FULLCHECKLISTRESPONSE']._serialized_end=519
  _globals['_AISERVICE']._serialized_start=522
  _globals['_AISERVICE']._serialized_end=793
# @@protoc_insertion_point(module_scope)
